config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "en"}   do
    root "static_pages#home"

    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
    get "password_resets/new"
    get "password_resets/edit"
    get "sessions/new"
    resources :users
    resources :account_activations, only: :edit
    resources :password_resets, only: [:new, :create, :edit, :update]
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t(:translate, item: t("translates.the")) %>
      <%= link_to t("RORT"), "https://www.railstutorial.org/" %>
    <%= t(:translate, item: t("translates.by"))%>
      <%= link_to t("translates.Michael_Hartl"),
      "http://www.michaelhartl.com/" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("static_pages.about.title"), about_path %></li>
      <li><%= link_to t("static_pages.contact.title"), contact_path %></li>
      <li><%= link_to t(:translate, item: t("translates.new")), "http://news.railstutorial.org/" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("static_pages.home.title"), root_path %></li>
        <li><%= link_to t("static_pages.help.title"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t(:translate, item: t("translates.account")) %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(:translate, item: t("translates.profile")),
                current_user %></li>
              <li><%= link_to t(:translate, item: t("translates.setting")),
                edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(:translate, item: t("translates.logout")),
                  logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(:translate, item: t("translates.login")),
            login_path %></li>
        <% end %>
        <li><%= link_to_unless I18n.locale == :vn,
          t("static_pages.array_language.al2"), locale: :vn %></li>
        <li><%= link_to_unless I18n.locale == :en,
          t("static_pages.array_language.al1"), locale: :en %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>